### ISSUE TITLE
Update NLog to latest version, instead of BETA

### ISSUE THREAD

**Issue by snakefoot** [awesome-inc/NWaveform#10]
https://github.com/awesome-inc/NWaveform/blob/9a66840d268743df296982f1ebf455afed745b01/NWaveform.App/packages.config#L14
NLog 4.5.0 RTM has been released for NetCore: https://www.nuget.org/packages/NLog/

**Comment by mkoertgen** [comment]
The sample app is nothing we ship but thanks for hinting on the update.

**Comment by mkoertgen** [comment]
@snakefoot I just checked back: The latest stable should be 4.5.11, right? That would be a downgrade, effectively.

**Comment by mkoertgen** [comment]
Just consolidated the NuGet dependencies.
